version: '3.9'

services:
  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookmarks_db
    ports:
      - "5432:5432"
    volumes:
      - psql222:/var/lib/postgresql/data
    networks:
      - my_network

  elastic:
    image: elasticsearch:8.15.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "9200:9200"
    networks:
      - my_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - my_network

volumes:
  psql222:

networks:
  my_network: